### ISSUE TITLE
npm run start 

### ISSUE THREAD

**Issue by aminalimadadi** [dappuniversity/starter_kit#46]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\webpack\lib\NormalModule.js:386:16)
    at C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\webpack\lib\NormalModule.js:418:10
    at C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\webpack\lib\NormalModule.js:293:13
    at C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\mechanic rayane\Documents\GitHub\starter_kit\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.1
if any body can help the localhost does not respond

**Comment by RexSan0x** [comment]
Faced the same issue. But i tried this and it fixed it ig:
In your package.json file, change this line:
`"start": "react-scripts start"`
to this line:
`"start": "react-scripts --openssl-legacy-provider start"`

Source: (https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported)
