### ISSUE TITLE
'react-scripts' is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by KevinJ1984** [dappuniversity/starter_kit#7]
$ npm run start

> eth-marketplace@0.1.0 start C:\Users\hw-kohagan\Documents\dapps\meme
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! eth-marketplace@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the eth-marketplace@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                                  ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\2020-05-20T11_2                                                                                                                                  6_14_393Z-debug.log

**Comment by KevinJ1984** [comment]
$ cat 2020-05-20T13_04_09_049Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hw-kohagan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.14.4
3 info using node@v8.11.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle eth-marketplace@0.1.0~prestart: eth-marketplace@0.1.0
6 info lifecycle eth-marketplace@0.1.0~start: eth-marketplace@0.1.0
7 verbose lifecycle eth-marketplace@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle eth-marketplace@0.1.0~start: PATH: C:\Users\hw-kohagan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\hw-kohagan\Documents\dapps\meme\node_modules\.bin;C:\Users\hw-kohagan\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\hw-kohagan\bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\OpenVPN\bin;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL Server\130\Tools\Binn;C:\Dwimperl\perl\bin;C:\Dwimperl\perl\site\bin;C:\Dwimperl\c\bin;C:\Program Files (x86)\DevDesktop\drush;C:\Program Files\PuTTY;C:\ProgramData\chocolatey\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\nodejs;C:\Program Files\dotnet;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommon;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.3.3\bin;C:\Users\hw-kohagan\AppData\Local\Microsoft\WindowsApps;C:\Users\hw-kohagan\AppData\Local\.meteor;C:\Users\hw-kohagan\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle eth-marketplace@0.1.0~start: CWD: C:\Users\hw-kohagan\Documents\dapps\meme
10 silly lifecycle eth-marketplace@0.1.0~start: Args: [ '/d /s /c', 'react-scripts start' ]
11 silly lifecycle eth-marketplace@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle eth-marketplace@0.1.0~start: Failed to exec start script
13 verbose stack Error: eth-marketplace@0.1.0 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\hw-kohagan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\hw-kohagan\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid eth-marketplace@0.1.0
15 verbose cwd C:\Users\hw-kohagan\Documents\dapps\meme
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hw-kohagan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v8.11.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error eth-marketplace@0.1.0 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the eth-marketplace@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by KevinJ1984** [comment]
$ npm run start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\2020-05-20T13_34_08_509Z-debug.log

log file:


0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\hw-kohagan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.14.4
3 info using node@v8.11.3
4 verbose stack Error: ENOENT: no such file or directory, open 'C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\package.json'
5 verbose cwd C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs
6 verbose Windows_NT 10.0.18362
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hw-kohagan\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
8 verbose node v8.11.3
9 verbose npm  v6.14.4
10 error code ENOENT
11 error syscall open
12 error path C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\package.json
13 error errno -4058
14 error enoent ENOENT: no such file or directory, open 'C:\Users\hw-kohagan\AppData\Roaming\npm-cache\_logs\package.json'
15 error enoent This is related to npm not being able to find a file.
16 verbose exit [ -4058, true ]
~

**Comment by dschoon** [comment]
Did you run `npm install` first?
